### ISSUE TITLE
In new minetest 5.9 causes fault

### ISSUE THREAD

**Issue by sfence** [HybridDog/vector_extras#6]
When is used with painting mod, this happens https://pastebin.com/jYbU7UZe

Probably because the `vector.zero` method is overwritten.

I can reproduce it only in one world. I have no idea why.

**Comment by HybridDog** [comment]
Thanks for reporting this.
I couldn't reproduce this; executing `vector.zero()` has succeeded for me when I tried it. 

Nonetheless, I have removed deprecated functionality from this mod now (Release v1.0.0), including vector.zero, so it should no longer crash.

**Comment by sfence** [comment]
I updated the mod to the actual master and the error disappears. Thanks.
